ln -s "$HOME/.dotfiles/git/.gitconfig" "$HOME/.gitconfig"
ln -s "$HOME/.dotfiles/lazy/" "$HOME/.gitignore_global"
ln -s "$HOME/.dotfiles/lazy/" "$HOME/.zim/lazy"
ln -s "$HOME/.dotfiles/shell/.hushlogin" "$HOME/.hushlogin"
ln -s "$HOME/.dotfiles/shell/.zshrc" "$HOME/.zshrc"
ln -s "$HOME/.dotfiles/shell/.zshenv" "$HOME/.zshenv"
ln -s "$HOME/.dotfiles/shell/.zprofile" "$HOME/.zprofile"
ln -s "$HOME/.dotfiles/shell/.zimrc" "$HOME/.zimrc"
