github.com:
    user: daniel-enqz
    oauth_token: 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
    git_protocol: ssh
    use_keychain: true
    add_keys_to_agent: true
    identity_file: ~/.ssh/id_ed25519
