#!/bin/bash
name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint shell scripts
      run: shellcheck $(find . -name '*.sh' -not -path './startup.sh')
