#!/bin/bash
name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DOTFILES_DIR: /home/runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint shell scripts
      run: shellcheck -C -e SC2034 $(find . -name '*.sh' -not -path './lazy/*' -not -path './shell/lib/_functions/imports.sh' -not -path './shell/init.sh' -not -path './shell/exports.sh')
