#!/bin/bash
name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DOTFILES_DIR: /home/runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint shell scripts
      run: shellcheck -C $(find . -name '*.sh' -not -path './startup/startup.sh')
